### ISSUE TITLE
webwxgetcontact获取联系人列表时的问题

### ISSUE THREAD

**Issue by glovebx** [0x5e/wechat-deleted-friends#10]
一次能把所有联系人全部都获取吗？我记得之前在C#里模拟操作时一次最多获取100人，供参考。

**Comment by 0x5e** [comment]
是全部获取的呀,分组是因为,群聊人数不能超过40人(知乎上是这么说的),所以我设了35人一组

**Comment by glovebx** [comment]
测试了确实全部获取的，谢谢
