### ISSUE TITLE
兼容python3

### ISSUE THREAD

**Issue by a284628487** [0x5e/wechat-deleted-friends#102]
python3下会有个错误，在484行，
map(lambda x: '#', progress[:(progress_len \* (i + 1)) / group_num]))
其实很简单，改成
map(lambda x: '#', progress[:int((progress_len \* (i + 1)) / group_num])))
就行了
暂时没发现其它的问题

**Comment by musicyy** [comment]
map(lambda x: '#', progress[:int((progress_len \* (i + 1)) / group_num)]))
应该是这样吧？
