### ISSUE TITLE
最新这个更新的找不到好友了，一直是0位好友，直接结束？

### ISSUE THREAD

**Issue by ErisonChen** [0x5e/wechat-deleted-friends#107]
最新这个更新的找不到好友了，一直是0位好友，直接结束？

**Comment by roundyxu** [comment]
@0x5e
ssl
0x5e committed 3 days ago 这个版本好像可以，后面的版本好像不行了，你可以试试看看是不是这样。

**Comment by 0x5e** [comment]
把这行注释了试一下
ssl._create_default_https_context = ssl._create_unverified_context
之前是有人用不了才加上的
#91
