### ISSUE TITLE
python2 python3 都不可用

### ISSUE THREAD

**Issue by leadscloud** [0x5e/wechat-deleted-friends#113]
python2.6
��程序的查询结果可能会引起一些心理上的不适,请小心使用...
��在获取二维码图片...
��使用微信扫描二维码以登�
��功扫描,请在手机上点击确认以登录
��在登录...
��启心跳线�
��讯录共0位好�
��始查找...

结果汇总完毕,20s后可重试...
---------- 被删除的好友列表(共0人) ----------
## �

��车键退出...
Unhandled exception in thread started by
Error in sys.excepthook:

Original exception was:

python3 不用说了，问题多，这个源码那么多人关注，为什么没人优化下呢。

**Comment by 0x5e** [comment]
用2.7.10试试
#91 
没有windows的测试环境,不清楚是ssl还是cookie的问题,麻烦各位帮忙试下吧
