### ISSUE TITLE
Win10 PYTHON2.7总显示0人删除

### ISSUE THREAD

**Issue by Freshield** [0x5e/wechat-deleted-friends#114]
一开始程序的时候还能显示被谁删了 但是进度条走了点后就一直显示0人删除了 嘛 觉得再怎么肯定不会都是0人删除我 所以感觉可能是不是程序是有点问题 还是说也是因为频率问题被腾讯拉小黑屋了？
程序显示如下：

C:\Users\FRESHIELD\Desktop\test\wechat-helper\wechat-deleted-friends>wdf.py
本程序的查询结果可能会引起一些心理上的不适,请小心使用...
开始
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
正在登录...
通讯录共1066位好友
开始查找...
[#-------------------------------------------------]
新发现你被12人删除
◇染指為红颜╮
melodydie78@gmai
wangxin
JSis
123(王世民)
请叫我教皇
(??_?`)
Jeremy xu
<span class="emoji emoji1f468"></span><span class="emoji emoji1f476"></span>
hauw(加拿大hauw)
花雀
蒙城韩国化妆品代购(加拿大干婕)
正在继续查找,请耐心等待...
[###-----------------------------------------------]
新发现你被3人删除
张小胖
.....(加拿大王树博)
AA00金刚芭比polla <span class="emoji emoji1f622"></span>
正在继续查找,请耐心等待...
[####----------------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[######--------------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[########------------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#########-----------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[###########---------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[############--------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[##############------------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[################----------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#################---------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[###################-------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[####################------------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[######################----------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[########################--------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#########################-------------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[###########################-----------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#############################---------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[##############################--------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[################################------------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#################################-----------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[###################################---------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#####################################-------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[######################################------------]
新发现你被0人删除
正在继续查找,请耐心等待...
[########################################----------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#########################################---------]
新发现你被0人删除
正在继续查找,请耐心等待...
[###########################################-------]
新发现你被0人删除
正在继续查找,请耐心等待...
[#############################################-----]
新发现你被0人删除
正在继续查找,请耐心等待...
[##############################################----]
新发现你被0人删除
正在继续查找,请耐心等待...
[################################################--]
新发现你被0人删除
正在继续查找,请耐心等待...
[##################################################]
新发现你被0人删除

结果汇总完毕,20s后可重试...
---------- 被删除的好友列表(共15人) ----------
◇染指為红颜╮
melodydie78@gmai
wangxin
JSis
123(王世民)
请叫我教皇
(??_?`)
Jeremy xu

hauw(加拿大hauw)
花雀
蒙城韩国化妆品代购(加拿大干婕)
张小胖
.....(加拿大王树博)
AA00金刚芭比polla

---

结束

**Comment by 0x5e** [comment]
现在还有这问题吗,已经加上心跳了

**Comment by Freshield** [comment]
加上心跳之后 就是直接显示操作频繁了。。。哈

C:\Users\FRESHIELD\Desktop\wechat-deleted-friends-master\wechat-deleted-friends-master>wdf.py
本程序的查询结果可能会引起一些心理上的不适,请小心使用...
正在获取二维码图片...
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
正在登录...
开启心跳线程
通讯录共1066位好友
开始查找...
[ # ------------------------------------------------- ] 新发现你被12人删除
◇染指為红颜╮
melodydie78@gmai
wangxin
JSis
123(王世民)
请叫我教皇
(??_?`)
Jeremy xu
<span class="emoji emoji1f468"></span><span class="emoji emoji1f476"></span>
hauw(加拿大hauw)
花雀
蒙城韩国化妆品代购(加拿大干婕)
正在继续查找,请耐心等待...
[ ### ----------------------------------------------- ] 新发现你被3人删除
张小胖
.....(加拿大王树博)
AA00金刚芭比polla <span class="emoji emoji1f622"></span>
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ #### ---------------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ###### -------------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ######## ------------------------------------------ ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ######### ----------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ########### --------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ############ -------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ############## ------------------------------------ ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
[ ################ ---------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 操作太频繁，请稍后再试。
func: deleteMember, Ret: -1, ErrMsg:
[ ################# --------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...

**Comment by 0x5e** [comment]
#116 这个 没办法了 ..
