### ISSUE TITLE
File "wdf.py", line 568, in <module>

### ISSUE THREAD

**Issue by sicaboy** [0x5e/wechat-deleted-friends#129]
File "wdf.py", line 568, in <module>

**Comment by 0x5e** [comment]
in where?

**Comment by hondajojo** [comment]
```
Traceback (most recent call last):
  File "wdf.py", line 568, in <module>
    main()
  File "wdf.py", line 442, in main
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
```

**Comment by hondajojo** [comment]
用 python3 即可

**Comment by sicaboy** [comment]
File "wdf.py", line 6, in <module>
    import requests

**Comment by sicaboy** [comment]
python3 wdf.py 

Traceback (most recent call last):
  File "wdf.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'

Running on python3, MacOS

**Comment by sicaboy** [comment]
After installing 'requests', problem remains:

sudo easy_install pip
pip install requests

Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 501kB 57kB/s 
Installing collected packages: requests
Successfully installed requests-2.9.1

python3 wdf.py 
Traceback (most recent call last):
  File "wdf.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by 0x5e** [comment]
@sicaboy pip3 install requests试下，你可能装到py2上去了

**Comment by sicaboy** [comment]
$ pip3 install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages

好像还是不行

**Comment by sicaboy** [comment]
可以了，谢谢
