### ISSUE TITLE
弱弱的一个小建议，不知道有没有人提过。

### ISSUE THREAD

**Issue by yu1ec** [0x5e/wechat-deleted-friends#132]
我弱弱的提一个建议，就上说，封锁肯定存在，这个没办法避免，但是，我等了几个小时，可以继续玩了，但是，有得从头开始，可是，里面的好友我全测过了，都是真的好友，但后面不能测到的好友，可能就一辈子测不到了，所以，我能不能提一下就是把已经测试过的好友加个缓存记录，这样可以跳过这些测试过的好友继续去测试那些没测试过的，单让，我只有10个好友，所以也不存在这个问题，啊哈哈哈哈！

**Comment by 0x5e** [comment]
恩..是可以这样
最近好忙,没空弄了😊有兴趣可以提个PR哈

**Comment by yu1ec** [comment]
吼吼，原来是这样额，好嘛，等空了，自己玩玩看~
