### ISSUE TITLE
为什么加进群组的朋友最后没了？

### ISSUE THREAD

**Issue by gaoxinge** [0x5e/wechat-deleted-friends#139]
你好，readme说该项目的原理是通过新建群组加人，加进的是未删的，加不进的是已删的。我好奇最后那些加进来的人都到哪里去了？谢谢。

**Comment by zhengze** [comment]
你好，你不发信息的话，群里的人根本不知道你新建了个群聊，所以如果你只是测试自己是否被删除，就别发信息。

来自 魅族 MX4

-------- 原始邮件 --------
发件人：gaoxinge notifications@github.com
时间：周一 5月30日 08:33
收件人：0x5e/wechat-deleted-friends wechat-deleted-friends@noreply.github.com
主题：[0x5e/wechat-deleted-friends] 为什么加进群组的朋友最后没了？ (#139)

**Comment by gaoxinge** [comment]
原来还有这一步，真是太谢谢了。
