### ISSUE TITLE
好友多的时候后面好像就不管用了

### ISSUE THREAD

**Issue by jungledrum** [0x5e/wechat-deleted-friends#14]
目测，到第7组的时候就都为0个了，应该是出bug了。还没调试，先反馈一下。

**Comment by 0x5e** [comment]
这个不一定,你调试下看看BaseRequest里的Ret是否为0,0是正常返回

**Comment by 99api** [comment]
3000多个好友，到后面都找不到了

**Comment by xiangzhai** [comment]
@jungledrum 嗯呐，qwx https://github.com/xiangzhai/qwx 的群发也是有这个限制。。。

**Comment by XGHeaven** [comment]
可能是并发量太高，微信给禁止了吧

**Comment by xiangzhai** [comment]
@XGHeaven 群发消息的时候，遍历通讯录中用户信息列表 https://github.com/xiangzhai/qwx/blob/master/qml/ChatView.qml#L291 当发到第N个，有时候qwx会被服务器踢掉

**Comment by ygweric** [comment]
多执行几次试试
