### ISSUE TITLE
addMember, Ret: 1205

### ISSUE THREAD

**Issue by lotosli** [0x5e/wechat-deleted-friends#145]
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 
func: deleteMember, Ret: 1205, ErrMsg: 
[ # ------------------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 
func: deleteMember, Ret: 1205, ErrMsg: 
[ # ------------------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 
func: deleteMember, Ret: 1205, ErrMsg: 
[ # ------------------------------------------------- ] 新发现你被0人删除
正在继续查找,请耐心等待...
func: addMember, Ret: 1205, ErrMsg: 
func: deleteMember, Ret: 1205, ErrMsg: 
[ # ------------------------------------------------- ] 新发现你被0人删除

mac
python 2.7

**Comment by 0x5e** [comment]
接口限制了，已经不能用啦~参见readme
