### ISSUE TITLE
since when does wechat have open api?

### ISSUE THREAD

**Issue by zzz6519003** [0x5e/wechat-deleted-friends#19]
XD :beer:

**Comment by 0x5e** [comment]
并没有,可以用chrome调试

**Comment by zzz6519003** [comment]
:+1:

2016-01-05 9:37 GMT+08:00 gaosen notifications@github.com:

> 并没有,可以用chrome调试
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/0x5e/wechat-deleted-friends/issues/19#issuecomment-168864603
> .

## 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  http://about.me/zzz6519003
