### ISSUE TITLE
有漏啊 删除的用户没检测出来

### ISSUE THREAD

**Issue by captain-miao** [0x5e/wechat-deleted-friends#24]
关注修复～

**Comment by limitMe** [comment]
同样有这个问题，至少知道被两名好友删除，未被检测出。

**Comment by mengyyy** [comment]
我确认被拉黑的一个不会检测出来

**Comment by xiangzhai** [comment]
@captain-miao https://github.com/0x5e/wechat-deleted-friends/issues/14
