### ISSUE TITLE
别人能知道拉他进群嘛？

### ISSUE THREAD

**Issue by iScript** [0x5e/wechat-deleted-friends#31]
如果知道就没意义了。。

**Comment by 0x5e** [comment]
readme写了呀 只要不讲话别人是看不到群的..

**Comment by hamjl** [comment]
黑名单能查到吗？

**Comment by mengyyy** [comment]
黑名单不会显示  但是会拒绝加群

**Comment by Meriky** [comment]
但是刚才我用脚本崩溃了之后用手机再上，在我微信里还留了一个群，要是崩溃了的话别人应该会看到的，当时崩了的时候群里面还有一些个好友

好吧 我懂了 即使自己能看到 如果建群的人不说话 这些人还是看不到的

**Comment by kingtami** [comment]
我这边显示4个删除好友,实际上都是没有删除的,还在联系呢....什么情况?

**Comment by 0x5e** [comment]
@kingtami 他们有回你吗,没有的话可能只是关了加好友验证吧

**Comment by ghost** [comment]
如果长时间没有聊过的，会发一个邀请加入群聊的链接

**Comment by 0x5e** [comment]
@haython 如果对方把你删了,并且关闭了"加好友验证",会这样
不过只是客户端,网页端不会发的
