### ISSUE TITLE
调用weixin http api会有卡主的情况

### ISSUE THREAD

**Issue by rfyiamcool** [0x5e/wechat-deleted-friends#32]
调用weixin http api会有卡主的情况

**Comment by xiangzhai** [comment]
@rfyiamcool 因为需要轮询保持心跳，否则会被服务器踢掉，而Sync本身是会超时的，需要做成异步 https://github.com/xiangzhai/qwx/blob/master/qml/NavigatorView.qml#L101

**Comment by 0x5e** [comment]
@xiangzhai 谢谢,之前没想到这个问题 因为放了好多回车继续只是想方便调试.. 如果去掉的话应该可以在一个心跳周期内完成查询吧

**Comment by xiangzhai** [comment]
@0x5e 建议心跳轮询放在单独一个线程里循环，命令行交互还是有必要的 ;-)

**Comment by 0x5e** [comment]
@xiangzhai 好的,有时间做,最近有些忙😁

**Comment by 0x5e** [comment]
已加上
