### ISSUE TITLE
改造成web版 ，获取不到联系人

### ISSUE THREAD

**Issue by yss0729** [0x5e/wechat-deleted-friends#45]
先谢谢作者提供的这个工具，我现在想在这个基础上改造成一个web版的 
但是中间遇到了一些奇怪的问题 
我前台通过ajax 阻塞的方式 依次按顺序请求
从  获取uuid -> 获取二维码并扫描 -> 登录成功 -> 初始化成功(Debug下已生成json文件 可以看到我的好友列表) - > 获取联系人webwxgetcontact 在这个函数里却始终获取不到MemberList  我用打印出来的url访问页面得到的json数据是
{
"BaseResponse": {
"Ret": 1,
"ErrMsg": ""
}
,
"MemberCount": 0,
"MemberList": [],
"Seq": 0
}

我很费解，调试了很久，也打印出了各个环节得到的 global 变量， 都能保持一致性，为什么偏偏这个环节获取不到了呢。

**Comment by greplay** [comment]
正解有突破分下一下

**Comment by yss0729** [comment]
@grapeot  啥意思？

**Comment by yss0729** [comment]
@gforetell  啥意思？

**Comment by 0x5e** [comment]
看一下cookie,登录后好像是需要cookie的

**Comment by 0x5e** [comment]
要不要试试能否做成chrome插件的形式,直接在微信网页版的网页内做操作,感觉这样会方便点..
js不太熟悉所以还是用了py..命令行的用户体验确实不是很好

**Comment by yss0729** [comment]
@0x5e 哈哈  已经调试好了  貌似我在那个函数里 请求的时候 也加了 BaseRequest 貌似就好了 不知道是不是cookie的原因哈 
url = base_uri + '/webwxgetcontact?pass_ticket=%s&skey=%s&r=%s' % (pass_ticket, skey, int(time.time()))
    params = {
        'BaseRequest': BaseRequest
    }
    request = urllib2.Request(url = url,data = json.dumps(params))
