### ISSUE TITLE
越到后面越快而且后面的结果都是0，是不是被微信服务器限制了？

### ISSUE THREAD

**Issue by greatpresident** [0x5e/wechat-deleted-friends#46]
前几组比较慢，有结果；越到后面越快而且后面的结果都是0，是不是被微信服务器限制了？
没有看到错误日志打印出来，作者能否看看每分钟是否有建群限制？

**Comment by 0x5e** [comment]
#32 也许是这个问题

**Comment by 0x5e** [comment]
好像是做限制了,"操作太频繁，请稍后再试"... 之前很频繁测也没出现过的样子

**Comment by zhujia18** [comment]
我也正在看代码，不知道服务器限制的时间间隔是多久，看朋友圈别的朋友操作的时候还没有这个问题呢

**Comment by 0x5e** [comment]
#59
