### ISSUE TITLE
如果已经登录了 OS X 版微信客户端，那么会卡在「正在登录」

### ISSUE THREAD

**Issue by namiwang** [0x5e/wechat-deleted-friends#51]
re-pro
1. 正常登录微信客户端
2. python wdf.py
3. 扫码
4. 显示「成功扫描」
5. 微信客户端被退出，提示在其它处登录
6. 显示「正在登录」
7. 然后就没有然后了

**Comment by golmic** [comment]
@nanowang 我没出现这种情况

**Comment by 0x5e** [comment]
网络不好吧 多试试?
