### ISSUE TITLE
重复测试时 后续显示的被删除个数为0

### ISSUE THREAD

**Issue by zminds** [0x5e/wechat-deleted-friends#59]
如题

**Comment by zhujia18** [comment]
看提示是由于操作过于频繁，服务器做限制了，我看朋友圈朋友测试的时候还没有提示频繁呢

**Comment by 0x5e** [comment]
是的 刚打印了提示 好像是微信加限制了…

**Comment by zhujia18** [comment]
我等了几分钟。。。再登录测试还是这样 - - ！估计是玩的人多，会给服务器带来并发，略显小气啊

**Comment by zminds** [comment]
确实是

开始查找...
 Everything is OK
 操作太频繁，请稍后再试。
 操作太频繁，请稍后再试。
 操作太频繁，请稍后再试。

---------- 被删除的好友列表 ----------

``` python
dic = json.loads(data)
    ChatRoomName = dic['ChatRoomName']
    MemberList = dic['MemberList']
    DeletedList = []
    for Member in MemberList:
        if Member['MemberStatus'] == 4:  # 被对方删除了
            DeletedList.append(Member['UserName'])

    ErrMsg = dic['BaseResponse']['ErrMsg']
    if len(ErrMsg) > 0:
        print(ErrMsg)
```

**Comment by zhujia18** [comment]
我在想是针对整个创建分组都做限制了，还是针对deviceID一类的做限制了
skey = ''
wxsid = ''
wxuin = ''
pass_ticket = ''
deviceId = 'e000000000000000'

**Comment by gangbo** [comment]
好友多的话就会提示操作太频繁

**Comment by zhujia18** [comment]
每个分组35人，我这里从第二个分组开始，就提示频繁了

**Comment by gangbo** [comment]
可以把频率调低一点

**Comment by 0x5e** [comment]
@zhujia18 和并发没关系吧,就是被微信限制了咯..刚试了下微信网页版也是如此

**Comment by 0x5e** [comment]
限制时间大概至少半小时..刚试了还是提示太频繁

**Comment by zhujia18** [comment]
如果在登录之后延时创建群添加好友，和删除群好友呢？

**Comment by 0x5e** [comment]
@zhujia18 应该是没戏了,这个其实微信想要限制还是很容易的,这脚本应该算是失效了吧😔

**Comment by heaventear** [comment]
@0x5e  本来还想打个安装包造福非程序员呢，开来也要放弃了。微信团队反应太迅速了。

star你这个repo的肯定潜伏着微信的码农哈哈

有成功破解微信原生客户端的吗

**Comment by zhujia18** [comment]
@heaventear 我还从deviceId上做了几次尝试。。。依旧无果，没摸索出来微信的策略是啥 - -！

**Comment by 0x5e** [comment]
@heaventear 会不会是回车键继续去掉的缘故..太频繁了才进黑名单的 哪位有兴趣再试试看哈

**Comment by heaventear** [comment]
@0x5e  肯定是微信内部人临时后台给打的补丁加的限制。不过有机会可以换个思路试试，现在的特征太明显了，和正常建群聊天差别太大。就像GFW检测翻墙一样，特征特明显，封了也不会错杀。

**Comment by heaventear** [comment]
来来来，微信内部的人出来冒个泡吧 。这个项目应该是国人做的star增长速度最快的一个repo了吧, @0x5e , 你本来可以继续创造新纪录的， 就这样被微信给扼杀了

**Comment by zhujia18** [comment]
@heaventear 仔细模拟好人的操作，我觉得微信会相对更难检测出来

**Comment by heaventear** [comment]
@zhujia18  那就要发消息，那样就没意义了

**Comment by zhujia18** [comment]
@heaventear 模拟人去创建群聊天的频率

**Comment by heaventear** [comment]
@zhujia18  这个频率是离散的。单单一条，比如10分钟内创建多个群，而且不发消息，这个特征就把这个脚本封的死死的。散了吧。不过 赞PO主的专研和分享精神 @0x5e

**Comment by sabrinaluo** [comment]
怀疑楼上是微信的卧底！ :laughing:

**Comment by xiangzhai** [comment]
@heaventear 不明白webwx为什么对群发 https://github.com/xiangzhai/qwx/blob/master/qml/ChatView.qml#L291 也做类似的限制，异步的 + sleep可以破吗？
