### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by hzwer** [0x5e/wechat-deleted-friends#6]
分组数没取整？我发了个pull request
用户昵称有表情时会输出代码，如 <span class="emoji emoji1f42f"></span>昵称
建议自动关闭二维码

**Comment by 0x5e** [comment]
有些用户的表情可以显示的,有些是<span>,可能是iOS和Android的不太一样..
关闭二维码这个,有什么好的办法吗,最好是三个平台都能用咯,一时想不出来= =

**Comment by hzwer** [comment]
不太懂怎么关闭

**Comment by Congee** [comment]
@0x5e 用subprocess模块替换system函数，记录pid然后你懂的

**Comment by 0x5e** [comment]
@Congee 谢谢,晚上我试下
