### ISSUE TITLE
这样一个代码库短短时间star数超过2300个，是不是作弊了？

### ISSUE THREAD

**Issue by xiemeilong** [0x5e/wechat-deleted-friends#63]

**Comment by sabrinaluo** [comment]
PO主那么屌，说不定写了一个程序自动注册github自动加星星呢 :smile:

**Comment by 0x5e** [comment]
😂这个真没有..

**Comment by xiemeilong** [comment]
中国程序员的代码库我知道的最高的也就3000多star，按你这速度，明天就要成第一了，中国程序员的兴趣点有点恶俗啊

**Comment by sabrinaluo** [comment]
@xiemeilong [vue.js](https://github.com/vuejs/vue)表示不服… :joy: 

PO主这个真的是抓住了“痛点”哟，程序员们终于可以极客起来，妈妈再也不担心我傻逼兮兮的群发什么“清一清微信”之类的信息啦。

建议PO主做个网页版，放到heroku上去，让其他 **!程序员** 也可以玩，这样妈妈就再也不用担心我收到“清一清微信”之类的信息啦 :smile:

**Comment by heaventear** [comment]
@sabrinaluo  把代码放在云端技术是可行的，不过肯定会被微信分分钟封死的。还是由客户端执行比较靠谱。

**Comment by 0x5e** [comment]
@xiemeilong 3000star离第一应该还是差了十万八千里吧,这哪里恶俗了...各有所爱嘛,其实我对谁删了我好友真的不在意,就是觉得能用脚本实现这么个小功能 本身比较好玩

**Comment by 0x5e** [comment]
@hzwer 现在已经被限制了,应该算是失效了..

**Comment by heaventear** [comment]
大家散了吧，微信的人再盯着呢呵呵

**Comment by zminds** [comment]
可惜没让他们加会儿班儿

**Comment by zane001** [comment]
我就冒个泡，反正我的微信好友也不多

**Comment by ffrankiefu** [comment]
当前哪个接口调用有限制？限制时间间隔是多少？

**Comment by zhujia18** [comment]
@Fansion 现在看应该是创建群聊天-删除群里好友这个过程被限制，限制时间从我这里测试将近30分钟

**Comment by ffrankiefu** [comment]
@zhujia18 刚才本地调试的时候忘了打日志，正在等下一次可测试，找出具体受限的接口(感觉很多接口都会限制调用时间)。

现在po主的逻辑是新建一个群组，然后更新群组成员。。
希望能调整判断逻辑回避这个时间限制。。

**Comment by presenthuang** [comment]
这么快就被ban了？

**Comment by ddbullfrog** [comment]
接口限制时间了

**Comment by go3k** [comment]
LZ这洋奴才思维真是醉了，井底之蛙。

**Comment by cuteluo1983** [comment]
修改下评论，感觉击中了痛点，python又一次显山露水。。。

**Comment by zhujia18** [comment]
这个也就是触及到了广大猿兴趣点或者是痛点吧？怎么感觉作弊的？还是怀疑中国猿的数量么？

**Comment by xiemeilong** [comment]
@0x5e 请问中国程序员在github上有超过4000star的project？

**Comment by HelKyle** [comment]
@xiemeilong 我觉得你这种理解有问题，你知道中国有多少人用微信吗？

**Comment by zhujia18** [comment]
@xiemeilong 别删楼，邮件通知有记录，随便给你一个https://github.com/onevcat/VVDocumenter-Xcode

**Comment by 0x5e** [comment]
@xiemeilong 反正iOS项目三四千 七八千的挺多的

**Comment by zhujia18** [comment]
@0x5e 我就是iOS猿

**Comment by AlanJN** [comment]
我来看评论的

**Comment by 0x5e** [comment]
@xiemeilong 
https://github.com/ipader/SwiftGuide
https://github.com/ibireme/YYText
https://github.com/bang590/JSPatch
https://github.com/numbbbbb/the-swift-programming-language-in-chinese
https://github.com/ChenYilong/iOS9AdaptationTips

**Comment by AlanJN** [comment]
@0x5e  直接甩给他 MJ啊 (逃

**Comment by 0x5e** [comment]
@AlanJN 不好意思..关注的不够全 让你见笑啦:)

**Comment by 0x5e** [comment]
其实这里都是我小号..不信我换一个回复你..

**Comment by lukay** [comment]
其实这里都是我小号..不信我换一个回复你..

**Comment by AlanJN** [comment]
@0x5e   哈哈 我在这里说MJ 是不是会被他的粉丝吊打

**Comment by zhujia18** [comment]
其实这里都是我小号..不信我换一个回复你..

**Comment by DualWield** [comment]
刚试了一下，还可以用

**Comment by zhujia18** [comment]
@DualWield - -! 还是被提示了。。。

**Comment by sabrinaluo** [comment]
恭喜PO主，今天trending开发者排名第一啦，repo排名前三！撒花～ :fireworks: 
https://github.com/trending/developers?since=daily
https://github.com/trending?since=daily

**Comment by DualWield** [comment]
@zhujia18 微信有分组吗？在哪里？我好像没有分过组

**Comment by sabrinaluo** [comment]
@DualWield 逻辑并不是一次性加所有人到一个群组里，而是分批加，只有第一批显示`everything is ok`，剩下的都是显示 `操作太频繁`，这样导致的就是你只能看到第一批中有多少人把你删了，后面的批次是看不到的

**Comment by DualWield** [comment]
@sabrinaluo 好像确实是的，没注意看log....但好像还是检测出来5个人了

```
Everything is OK当前,你被0人删除,好友共193人
 操作太频繁，请稍后再试。被5人删除,好友共193人
 操作太频繁，请稍后再试。 5人删除,好友共193人
 操作太频繁，请稍后再试。 5人删除,好友共193人
 操作太频繁，请稍后再试。 5人删除,好友共193人
```

**Comment by xiangzhai** [comment]
@0x5e deviceId用随机数 https://github.com/xiangzhai/qwx/blob/master/src/init.cpp#L23 应该可以解决@presenthuang 被ban的问题

**Comment by xiemeilong** [comment]
好吧，是我没见识了，看来搞IOS的兄弟比较喜欢上github，而我基本不关注移动开发的project.  感觉中国仗着人多，有点扰乱秩序的感觉，这样一个project实在感觉不应该这么多star，人家那些做框架做数据库做开发工具的的project情何以堪，那些才是真正对程序员更有用的东西。

**Comment by 0x5e** [comment]
@xiemeilong 不知道什么样才叫做秩序,让人家移动开发的同学情何以堪..大家都安安静静的写框架,开发数据库吗,然后呢,干嘛用呢..

**Comment by sabrinaluo** [comment]
不知道喷主是做哪块的，大前端圈表示不服…国人写的框架一搜一堆好吗

**Comment by xiemeilong** [comment]
@sabrinaluo 有攻击性的语言才叫喷，那么多人回复，唯独你说的话里有攻击性，你应该才是常做喷子的人吧

**Comment by AlanJN** [comment]
@0x5e 我去哭一会....被人看成扰乱秩序的了

**Comment by xiemeilong** [comment]
我只是表达一下自己的想法，毫无攻击性，我只是觉得star要加给对开发有帮助的项目。我在任何平台上都是只看不说，从来不做喷子。我unsubscribe，不要理我了。

**Comment by sabrinaluo** [comment]
@xiemeilong 我并没有故意针对你表现出**攻击性**，我平时说话就是这样的，如有冒犯还请多包涵。
另外，虽然…争论这个问题是没意义的…我也不是想要再次表现出攻击性…我不是为了输赢，我就是认真啊 :joy:  https://www.zhihu.com/question/20285684
