### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by MarcoQin** [0x5e/wechat-deleted-friends#7]
感谢作者。

手贱试用了一下，内心受到重大冲击，顿时觉得自己就是一傻逼。

感觉人生的目标突然清晰起来，动力也充足，比起那些喝腻的鸡汤，简直是一剂肾上腺素。

提个issue以示感谢，同时警示想要使用此脚本的旁友，使用前，需三思而后行。

**Comment by 0x5e** [comment]
😂
