### ISSUE TITLE
python 2.7.9 ssl错误

### ISSUE THREAD

**Issue by jincdream** [0x5e/wechat-deleted-friends#73]
解决参考： http://bookshadow.com/weblog/2015/04/22/sae-python-weibo-sdk-certificate-verify-failed/

错误
![887b413e-83c7-4a72-ad71-7346f8fb325a](https://cloud.githubusercontent.com/assets/4645261/12164041/45d73730-b54d-11e5-8243-95022bbdf0ef.jpg)

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
不会python ，就不提 pull request了。。
解决代码 ：

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by 0x5e** [comment]
谢谢,不知道是系统环境不同还是网络环境的问题..?这种情况是运营商的问题吗

**Comment by 0x5e** [comment]
已加上

**Comment by ffrankiefu** [comment]
@0x5e  @jincdream  我在调试运行的时候也出现了一次上面的错误(对某一批35人的更新请求失败)，后来ctrl+c 重新测试又能正常运行了。

**Comment by 0x5e** [comment]
可能加了这句导致部分同学获取不到通讯录,能否注释掉,升级至2.7.10以上版本试一下?
#91
