### ISSUE TITLE
一直是操作频繁，难道是被封了么？

### ISSUE THREAD

**Issue by ErisonChen** [0x5e/wechat-deleted-friends#74]
[ ###---------- ] (当前,你被0人删除,好友共%%人 操作太频繁，请稍后再试。
[ ####--------- ] (当前,你被0人删除,好友共%%人 操作太频繁，请稍后再试。
[ #####-------- ] (当前,你被0人删除,好友共%%人 操作太频繁，请稍后再试。
[ ########## ] (当前,你被0人删除,好友共%%人 操作太频繁，请稍后再试。

**Comment by zminds** [comment]
接口现在有时间限制了   隔一段儿时间就可以了  虽然还是会提示操作频繁但是能查出被删除的人

**Comment by 0x5e** [comment]
#75
