### ISSUE TITLE
操作过于频繁怎么破啊啊啊

### ISSUE THREAD

**Issue by Cool-Y** [0x5e/wechat-deleted-friends#75]

**Comment by ffrankiefu** [comment]
怀疑网页版的/webwxcreatechatroom接口和/webwxupdatechatroom接口都被封了。

有测试成功的么？

**Comment by gclsoft** [comment]
一样的问题

**Comment by ffrankiefu** [comment]
@gclsoft 之前还能检测第一批35人中是否有删了自己的，现在/webwxcreatechatroom接口直接返回“Ret: 1, ErrMsg: 操作太频繁，请稍后再试。”。

目测接口已经被封了。

**Comment by HAN-BOY** [comment]
刚刚试了下，分成20个人一组，前二十个ok，后面也不行

**Comment by Cool-Y** [comment]
@Fansion 刚刚试了下，分成20个人一组，前二十个ok，后面也不行，会不会要把频率降低

**Comment by BeibinLi** [comment]
用了 time.sleep(1) 也不行。

**Comment by gclsoft** [comment]
time.sleep 多一点时间看看

**Comment by 0x5e** [comment]
如果微信频率限制的周期设的长一点，半小时只能新建或者添加一个讨论组，那就不用sleep了 基本不可行了…

**Comment by Gilbert1024** [comment]
too many attempts，感觉接口GG。。。

**Comment by ffrankiefu** [comment]
@Gilbert1024   接口没GG，/webwxupdatechatroom接口调用需要时间间隔(20s左右)。

**Comment by 0x5e** [comment]
@Fansion 谢谢测试~

**Comment by ffrankiefu** [comment]
@0x5e  之前用小号(没几个好友)测试的，由于好友数为个位数很快出结果，然后命令行继续测试发现还能给正确结果且无“操作频繁”提示，就考虑sleep了。测试了几个时间，发现sleep 15s可行，13s就不可行了。

**Comment by 0x5e** [comment]
好友多的话可能会出现 #14 的问题,需要发心跳 我有空加一下..

**Comment by ffrankiefu** [comment]
现在接口调用的时间间隔限制好像变长了，如果出现“操作频繁”提示 将sleep时间设到25s左右 再试试。

**Comment by firedent** [comment]
151位好友，20一组，时间间隔60。开始第一组的时候显示“过于频繁”,之后一切正常.怀疑是程序逻辑问题。

**Comment by YummyYang** [comment]
估计不是程序逻辑的问题，个人估计是微信服务器端进行了限制：
下午测试了几次，前2次都是OK ,但后来不行了。
好友数4xx，
前2次能看到有几个是删了我的（也就是我被删除），但后来看不到，Ret值也变为了 1205：
新发现你被0人删除
正在继续查找,请耐心等待...
{
"BaseResponse": {
"Ret": 1205,
"ErrMsg": ""
}
,
"Topic": "",
"PYInitial": "",
"QuanPin": "",
"MemberCount": 0,
"MemberList": [],
"ChatRoomName": "",
"BlackList": ""
}

**Comment by Cheng-H-Y** [comment]
感觉是对请求ip限制了，提示请稍后之后，换了微信账号测试，还是请稍后，一组都测不完

**Comment by liaohuqiu** [comment]
目前的情况：30s 创建，删除，一共四次之后，还有可能被限制。

**Comment by lixi0912** [comment]
间隔60，4组35个，到第三组就被限制了

**Comment by never615** [comment]
第三组被限制

**Comment by XGHeaven** [comment]
如果总是提示操作很频繁的话，可以登录网页端试一下，如果网页端也是提示很频繁的话，估计就是被限制了。

**Comment by feikiss** [comment]
这种方式已经不好玩了。

**Comment by lixingcong** [comment]
我的是128个好友，分成20人一组，间隔60s

第一二组没问题，第三组就提示频繁操作。
我就等到结束，中途一直是频繁操作。

结果进去手机微信数了数拉进群里面的成员记录，刚刚好是128人。

也就是说没有人删掉我，但是检测提示频繁操作还是能拉人进去群的。

**Comment by sharpdeep** [comment]
我有99个好友，分成35人一组，每组间隔60s
第一二组没问题，到了第三组也出现了错误提示[操作频繁]

还有一个很奇怪的现象，我昨晚一开始有错误提示，等了一两个小时就由可以建群。

可是今天早上又出现了错误提示，在此之前应该有十几个小时没用到接口，今天晚上测试的时候又可以了，出现了刚才所说的情况。

**Comment by Ecareyu** [comment]
我弱弱的提一个建议，就上说，封锁肯定存在，这个没办法避免，但是，我等了几个小时，可以继续玩了，但是，有得从头开始，可是，里面的好友我全测过了，都是真的好友，但后面不能测到的好友，可能就一辈子测不到了，所以，我能不能提一下就是把已经测试过的好友加个缓存记录，这样可以跳过这些测试过的好友继续去测试那些没测试过的，单让，我只有10个好友，所以也不存在这个问题，哈哈哈哈啊
