### ISSUE TITLE
发现搜索结果有个别没有删我好友的朋友，也被列在结果列表里了

### ISSUE THREAD

**Issue by codeMonkeyWang** [0x5e/wechat-deleted-friends#9]
经过手动测试，发现这些好友无法被直接拉入群的（群里只有我一个人），但发入群邀请和聊天都正常。不知道是否和微信的版本有关系。

**Comment by 0x5e** [comment]
可能对方把"加我为朋友时需要验证"给关了,这样的话加不进群但是私聊能发出
我也不太确定,你看下他的朋友圈是怎么样的?

**Comment by 0x5e** [comment]
所以这些好友应该还是把你给删了的
