### ISSUE TITLE
webwxgetcontact 函数返回的数据

### ISSUE THREAD

**Issue by vfmqer** [0x5e/wechat-deleted-friends#95]
![image](https://cloud.githubusercontent.com/assets/12101119/12221803/68ac6f52-b7e4-11e5-9354-9406b1170439.png)

这样的数据返回错了吧？有没有人能提示一下是什么问题的

**Comment by Yoge-Code** [comment]
我也是返回这样的数据格式，是不是微信降权了

```
 'appid': 'wx782c26e4c19acffb',
```

这个 appid？

**Comment by david9ml** [comment]
我也是

**Comment by 0x5e** [comment]
#91
